# Generated by Django 2.1.4 on 2019-02-05 13:55

import django.core.validators
from django.db import migrations, models
import testuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(3)])),
                ('join_date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(8)])),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=testuser.models.upload_to)),
            ],
        ),
    ]
